pub mod command;
pub mod config;
pub mod context;
pub mod error;
pub mod event;
pub mod ide;
pub mod permissions;
pub mod ports;
pub mod server_protocol;
pub mod session;
pub mod status;
pub mod tool_approval;

pub use command::Command;
pub use config::ResolvedConfig;
pub use context::{CommandContext, SessionMeta};
pub use error::{ConfigError, ExecutionError, PublishError, ShutdownError};
pub use event::{Event, EventId, EventPayload, EventScope};
pub use ide::{detect_ide, ide_cmd, ide_name, IdeInfo};
pub use permissions::{PermissionAction, PermissionRule};
pub use ports::ToolApprover;
pub use ports::TranscriptRecorder;
pub use ports::{CommandExecutor, EventPublisher, PathOperation, PermissionPolicy};
pub use session::{MessageId, MessageRole, SessionId, SessionInfo, StoredMessage, StoredToolCall};
pub use status::SessionStatus;
pub use tool_approval::ToolApprovalRequest;
