[package]
name = "rustcode-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rustcode-core = { path = "../rustcode-core" }
rustcode-state = { path = "../rustcode-state" }
thiserror.workspace = true
tokio.workspace = true
ratatui.workspace = true
crossterm.workspace = true

[lints]
workspace = true
