[package]
name = "rustcode"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
clap.workspace = true
rustcode-auth = { path = "../rustcode-auth" }
rustcode-config = { path = "../rustcode-config" }
rustcode-core = { path = "../rustcode-core" }
rustcode-engine = { path = "../rustcode-engine" }
rustcode-io = { path = "../rustcode-io" }
rustcode-llm = { path = "../rustcode-llm" }
rustcode-plugins = { path = "../rustcode-plugins" }
rustcode-state = { path = "../rustcode-state" }
rustcode-tui = { path = "../rustcode-tui" }
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
futures-util.workspace = true
tokio.workspace = true
tokio-util.workspace = true
rustcode-logging = { path = "../rustcode-logging" }
tracing.workspace = true
rpassword.workspace = true

[lints]
workspace = true
